project:
  type: website

website:
  title: "Laboratorio de estadística y matemáticas aplicadas"
  sidebar:
    logo: "images/logo.png"
    search: true
    pinned: true
    align: center
    style: "docked"
    collapse-level: 1
    contents:
      - index.qmd
      - section: 'Información general'
        contents:
          - services.qmd
          - horarios.qmd
          - linksasig.qmd
      - section: 'Links de interés' 
        contents:
        - links/python.qmd
        - links/r.qmd
        - links/julia.qmd
        - links/quarto.qmd
      - avancesProyectos.qmd
      - semilleros.qmd
      - noticias.qmd
      - text: '---'
      - text: Reservas
        href: https://outlook.office365.com/owa/calendar/LaboratoriodeMatematicas@javerianacaliedu.onmicrosoft.com/bookings/

  page-footer: 
    left: Esta página no representa las políticas de la universidad Javeriana

format:
  html:
    link-external-newwindow: true
    theme: 
      light: flatly
      dark: darkly
    toc: true